# SPDX-License-Identifier: GPL-2.0

# module name
MODULE_NAME ?= nornir
obj-m += $(MODULE_NAME).o

# configuration for the module
CONFIG_FILE ?= $(src)/../.config
include $(CONFIG_FILE)

# header files
ccflags-y += -I$(src)/include

# general compilation flags
ccflags-y += -Wunused-function
ccflags-y += -Wundef

# entry point
$(MODULE_NAME)-y += main.o

# common gadgets
include $(src)/common/Kbuild

# fs
include $(src)/fs/Kbuild

# libs
include $(src)/libs/Kbuild

# module
include $(src)/mod/Kbuild

# network
include $(src)/net/Kbuild

# process subsystem
include $(src)/proc/Kbuild

# userland interface
include $(src)/uapi/Kbuild

# compilation flags for replacing internal macros
KBUILD_CFLAGS := $(filter-out -pg, $(KBUILD_CFLAGS))
KBUILD_CFLAGS := $(filter-out -mfentry, $(KBUILD_CFLAGS))
